sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
#alioss:
#  endpoint:
#  access-key-id:
#  access-key-secret:
#  bucket-name:
#sky:
#  datasource：
#    driver-class-name：com.mysql.cj.jdbc.Driver
#    host：localhost
#    port：3306
#    database：sky_take_out
#    username：root
#    password：root
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123456
    database: 10